# Generated by Django 3.0 on 2020-02-27 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0002_auto_20200228_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answer1',
        ),
        migrations.AlterField(
            model_name='sith',
            name='planet_learn',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(max_length=256, verbose_name='Вопрос'),
        ),
        migrations.CreateModel(
            name='Form_Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sith', to='bars.Sith')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurt', to='bars.Recurt')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='bars.Task')),
            ],
        ),
    ]
