# Generated by Django 3.0 on 2020-02-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0003_auto_20200228_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='right',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
