# Generated by Django 3.0 on 2020-02-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0004_auto_20200228_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='right',
        ),
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Task_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='bars.Task')),
            ],
        ),
    ]
