# Generated by Django 3.0 on 2020-02-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0006_auto_20200228_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sith',
            name='planet_learn',
            field=models.CharField(max_length=30, null=True, verbose_name='Планета на которой обучает'),
        ),
        migrations.AlterField(
            model_name='sith',
            name='sith_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя Ситха'),
        ),
    ]
