# Generated by Django 3.0 on 2020-02-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0007_auto_20200228_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Вопрос'),
        ),
    ]
