# Generated by Django 3.0 on 2020-02-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0008_auto_20200228_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(max_length=256, verbose_name='Вопрос'),
        ),
    ]
