# Generated by Django 3.0 on 2020-02-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0009_auto_20200228_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer1',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ответ #2'),
        ),
        migrations.AddField(
            model_name='task',
            name='answer2',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ответ #3'),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ответ #1'),
        ),
    ]
