# Generated by Django 3.0 on 2020-02-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0010_auto_20200228_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurt',
            name='question1',
            field=models.IntegerField(max_length=3, null=True, verbose_name='Ответ на первый вопрос 1 или 2 или 3'),
        ),
        migrations.AddField(
            model_name='recurt',
            name='question2',
            field=models.IntegerField(max_length=20, null=True, verbose_name='Ответ на второй вопрос 1 или 2 или 3'),
        ),
        migrations.AddField(
            model_name='recurt',
            name='question3',
            field=models.IntegerField(max_length=30, null=True, verbose_name='Ответ на третий вопрос 1 или 2 или 3'),
        ),
    ]
