# Generated by Django 3.0 on 2020-02-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0011_auto_20200228_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurt',
            name='question1',
            field=models.IntegerField(max_length=30, null=True, verbose_name='Ответ на первый вопрос 1 или 2 или 3'),
        ),
    ]
