# Generated by Django 3.0 on 2020-02-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bars', '0012_auto_20200228_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя рекуртера')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Почта рекуртера')),
            ],
        ),
        migrations.CreateModel(
            name='ShadowHand_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand', to='bars.ShadowHand')),
            ],
        ),
    ]
